// import { Users, Wrench, Zap, MapPin, Truck } from 'lucide-react';
//  export const statsData =  [
// 		{
// 			title: 'Civil Graduate Engineers',
// 			value: 48,
// 			// icon: <Users className='h-6 w-6' />,
// 			color: 'bg-blue-500',
// 			percentage: ((48 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Electrical Graduate Engineers',
// 			value: 3,
// 			// icon: <Zap className='h-6 w-6' />,
// 			color: 'bg-amber-500',
// 			percentage: ((3 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Mechanical Graduate Engineers',
// 			value: 3,
// 			// icon: <Wrench className='h-6 w-6' />,
// 			color: 'bg-emerald-500',
// 			percentage: ((3 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Diploma Engineers (Civil/Electrical/Mechanical)',
// 			value: 94,
// 			// icon: <GraduationCap className='h-6 w-6' />,
// 			color: 'bg-violet-500',
// 			percentage: ((94 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Surveyors',
// 			value: 11,
// 			// icon: <MapPin className='h-6 w-6' />,
// 			color: 'bg-cyan-600',
// 			percentage: ((11 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'CAD Operators',
// 			value: 3,
// 			// icon: <LayoutTemplate className='h-6 w-6' />,
// 			color: 'bg-yellow-500',
// 			percentage: ((3 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Equipment and Vehicle Operators',
// 			value: 65,
// 			// icon: <Truck className='h-6 w-6' />,
// 			color: 'bg-red-500',
// 			percentage: ((65 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Mechanic/Electrician/Welder/Fitter',
// 			value: 50,
// 			// icon: <Settings className='h-6 w-6' />,
// 			color: 'bg-orange-600',
// 			percentage: ((50 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Procurement Team',
// 			value: 18,
// 			// icon: <Package className='h-6 w-6' />,
// 			color: 'bg-lime-600',
// 			percentage: ((18 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Accounts Team',
// 			value: 32,
// 			// icon: <Calculator className='h-6 w-6' />,
// 			color: 'bg-sky-700',
// 			percentage: ((32 / totalEngineers) * 100).toFixed(1),
// 		},
// 		{
// 			title: 'Others',
// 			value: 159,
// 			// icon: <MoreHorizontal className='h-6 w-6' />,
// 			color: 'bg-gray-500',
// 			percentage: ((159 / totalEngineers) * 100).toFixed(1),
// 		},
// 	];
